### ISSUE TITLE
On Ubuntu MATE, starting egdme snap from MATE desktop causes black screen (but starting from LightDM works as expected)

### ISSUE THREAD

**Issue by GizmoChicken** [AlanGriffiths/egmde-snap#2]
The good:  After the updated egdme snap landed in the snap store, I successfully installed the latest egdme snap onto a fresh install of Ubuntu MATE 18.04, without need for any workaround.  After installation, and then logging _out_ of the MATE desktop, I’m able to start egdme from LightDM.  And once started from LightDM, egdme seems to be working as expected.

The bad:  But if I attempt to start egdme snap using “snap run egmde” from a terminal on the MATE desktop, the entire screen _invariably_ goes black.  I have a cursor, but nothing else.  I can’t exit the black screen using “ctrl-alt-bksp” or any other way that I could determine.

I’ll add that, _after_ observing the above issue, I installed Unity (“ubuntu-unity-desktop” meta-package from Universe) onto the same fresh install of Ubuntu MATE 18.04 mentioned above.  After logging into Unity from LightDM, I can start the egdme snap using “snap run egmde” from a terminal on the Unity desktop. And once started on Unity, egdme seems to be working as expected in a window on Unity.  So this doesn’t seem to have anything to do with the Ubuntu MATE base itself, but more likely with some aspect of a running MATE desktop.

Given that using “snap run egmde” from a terminal  is presumably meant mostly as an easy way to demonstrate and test (but not really use) egmde, I suppose this issue (especially if only occurring on the MATE desktop) could rightfully be placed in the “won’t fix” category, and I won't be offended if it is.  But I mention it here just in case it reveals an issue with Mir that needs to be resolved.

If helpful, I could also report this issue on the Mir issue tracker.  Or perhaps issues of this sort are already known are being addressed in Issue #497 on the Mir issue tracker?

**Comment by AlanGriffiths** [comment]
Thanks for that, this all sounds very odd. It sounds as though something in the MATE desktop is preventing Mir's Mir-on-X support from initializing (but I can't guess what might do that). Once that fails Mir tries to access resources owned by X.Org and triggers a bug (RAOF has recently found several in that area).

If that is the case, then the problem should be reproducible with mir-demos.

So, on the MATE desktop:

    sudo add-apt-repository --update ppa:mir-team/release
    sudo apt install mir-demos mir-graphics-drivers-desktop
    sudo apt install qterminal qtwayland5
    miral-app

If that get a black screen, then it is definitely a Mir problem and should be logged on the Mir tracker.

It will be a few days before I have time to spend on egmde (to set up a MATE install and try it there) if you could prove it is a Mir problem and log it there that could lead to a faster result.

**Comment by GizmoChicken** [comment]
After performing the above from a terminal on the MATE desktop, I get a black screen immediately after the "miral-app" step.  (For comparison, when performing the above on the same system, but from a terminal on the Unity desktop, Mir-on-X starts up fine after the "miral-app" step.)

I'm not quite sure what to look for in the logs, or even where best to look.  But if you can provide some guidance, I'll post what I find, wherever appropriate.  (Also, from the black screen, all I can think to do is power off.  If you can think of a more graceful exit (absent remote access), please suggest.)

I should note that I'm seeing this on a _very old_ test system, namely a Lenovo ThinkPad X61s (Intel Core2 Duo L7300 CPU).  In a few days, I could install Ubuntu MATE to a newer test system, just in case the issue is hardware specific.

**Comment by GizmoChicken** [comment]
UPDATE:  I tested for the above issues on Ubuntu MATE 18.04 freshly installed on an ASUS Q504UA (Intel Core i5-6200U CPU).  The findings are the same as described above for the ThinkPad, namely:

miral-app started from MATE terminal:   black screen
egmde snap started from MATE terminal:   black screen 
egmde snap started from LightDM:   works as expected

**Comment by AlanGriffiths** [comment]
Not an egmde-snap problem
